# Generated by Django 5.0 on 2023-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='images/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
